// Code generated by "stringer -type=Status"; DO NOT EDIT.

package user

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[active-1]
	_ = x[inActive-2]
	_ = x[lock-3]
	_ = x[banned-4]
	_ = x[pending-5]
	_ = x[suspended-6]
	_ = x[deleted-7]
}

const _Status_name = "noneactiveinActivelockbannedpendingsuspendeddeleted"

var _Status_index = [...]uint8{0, 4, 10, 18, 22, 28, 35, 44, 51}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
