name: Docker Image CI

on:
  push:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show directory contents
        run: ls -R

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download

      #     - name: Run tests
      #       run: go test -v ./...

      - name: Build binary
        run: go build -o ./cmd/rest_service ./cmd/main.go

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: mhthrh/rest_service
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest, ${{ github.sha }}
